//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityProductProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLPRODUCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLPRODUCT()
        {
            this.TBLSALES = new HashSet<TBLSALES>();
        }
    
        public int PRODUCTID { get; set; }
        public string PRODUCTNAME { get; set; }
        public string BRAND { get; set; }
        public Nullable<short> STOCK { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public Nullable<int> CATEGORY { get; set; }
    
        public virtual TBLCATEGORY TBLCATEGORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSALES> TBLSALES { get; set; }
    }
}
